### ISSUE TITLE
missing atcommands.user

### ISSUE THREAD

**Issue by bam80** [koshev-msk/luci-app-atinout#3]
Could you provide  file `/etc/config/atcommands.user` for initial set of commands?

**Comment by koshev-msk** [comment]
atcommands.user is a user commands for individual setup. You must include modified file via ImageBuilder or add more at-commands from source package build. Closed.

**Comment by bam80** [comment]
> atcommands.user is a user commands for individual setup.

Nice, but won't it be also reasonable to pre-populate it with some default set, as it's done here?
https://github.com/4IceG/luci-app-atinout-mod/blob/main/luci-app-atinout-mod/root/etc/config/atcommands.user
